on:
  schedule:
    - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: shovel-org/GithubActions@main
        env:
          GITH_EMAIL: bucks.mauls_0g@icloud.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SKIP_UPDATED: '1'
